spring:
  application:
    name: demomic-gateway
  config:
    import: optional:configserver:http://demomic-gateway:9000
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://localhost:9000
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/?(?<segment>.*), /$\{segment}
      default-filters:
        - SaveSession
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: demomic:gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://demomic-eureka:8070/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,env,refresh,info,gateway"
