spring:
  application:
    name: demomic-gateway
  config:
    import: optional:configserver:http://demomic-gateway:9000
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://localhost:9000/test
          predicates:
            - Path=/testt/**
          filters:
            - MyRouteFilter=Secret message

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://demomic-eureka:8070/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,env,refresh,info,gateway"
